### ISSUE TITLE
How about adding style guide?

### ISSUE THREAD

**Issue by nekketsuuu** [Drassil/git-wiki-theme#72]
**Is your feature request related to a problem? Please describe.**

Currently, some coding style of Liquid and YAML are not unified. This is a bit confusing when writing codes for pull requests.

Example 1: [Should we add spaces or not?](https://github.com/Drassil/git-wiki/blob/8c447f9f53c9630d525b1d1cdaf80038c875d944/_includes/git-wiki/components/action_btn/page_actions.html#L4)

```html
<a target="_blank" href="{{ site.github.repository_url }}/wiki/{{url | remove: '.html' | append: ''}}/_edit">Edit</a>
```

Example 2: [Should we add a space before colon?](https://github.com/Drassil/git-wiki/blob/e4dee648440da86091b350d12bb407d3a2e24ef6/_config.yml#L17)

```yaml
use_prose_io: true
service: github
search_engine : "js"
google_cse_token: 007197903287787072094:8rbvkeqo6qw
wiki_folder : "wiki"
permalink: /blog/posts/:year/:month/:day/:title:output_ext
```

**Describe the solution you'd like**

How about refactoring the current code and writing a style guide? One example I googled is [this](https://github.com/flathub/flathub/wiki/YAML-Style-Guide).
